jiango/cms/urls.py
# -*- coding: utf-8 -*-
# Created on 2015-10-13
# @author: Yefei
"""
from jiango.cms.urls import urlpatterns as cms_urls

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin_urls()),
    url(r'^api/captcha/', include('jiango.captcha.urls')),
    url(r'^api/', api_urls()),
    *cms_urls # root include
)
"""

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<path>.*)/p(?P<page>\d+)$', views.content_list, name='cms-list'),
    url(r'^(?P<path>.*)/(?P<content_id>\d+)$', views.content_show, name='cms-content'),
    url(r'^(?P<path>.*)$', views.index, name='cms-path'),
]

jiango/cms/article/models.py
# -*- coding: utf-8 -*-
# Created on 2015-10-15
# @author: Yefei
from django.db import models
from jiango.cms.models import ContentBase


class Article(ContentBase):
    title = models.CharField(u'标题', max_length=200)
    
    def __unicode__(self):
        return self.title


class Content(models.Model):
    article = models.OneToOneField(Article, primary_key=True, editable=False)
    content = models.TextField(u'内容')

jiango/cms/models.py
# -*- coding: utf-8 -*-
# Created on 2015-10-8
# @author: Yefei
from django.db import models
from django.db.models.deletion import SET_NULL
from django.dispatch import receiver
from django.db.models import signals
from django.db.models.query import QuerySet
from django.utils.datastructures import SortedDict
from django.utils.functional import cached_property
from django.core.cache import cache
from jiango.shortcuts import update_instance
from jiango.admin.models import User
from jiango.importlib import import_object
from .config import PATH_HELP, CONTENT_MODELS, LIST_PER_PAGE, FLAGS


INDEX_TEMPLATE_HELP = u'默认模版: cms/index'
LIST_TEMPLATE_HELP = u'默认模版: cms/list'
CONTENT_TEMPLATE_HELP = u'默认模版: cms/content'

PATH_TREE_CACHE_KEY = 'cms:path:tree'

PATH_DEPTH_FIRST = 1
PATH_DEPTH_ALL = -1


class PathQuerySet(QuerySet):
    # 取得指定路径下的栏目, depth 可以选择获取深度，1为一层 2为二层...
    # Path.objects.children('news')
    def children(self, path=u'', depth=PATH_DEPTH_FIRST):
        path = path.strip(' /')
        qs = self
        if path != '':
            qs = qs.filter(path__istartswith=path + '/')
        if depth != PATH_DEPTH_ALL:
            path_depth = path.count('/') + 1
            if depth == PATH_DEPTH_FIRST:
                qs = qs.filter(depth=path_depth)
            else:
                qs = qs.filter(depth__gte=path_depth,
                               depth__lte=path_depth + depth)
        return qs
    
    # 返回树形字典
    def tree(self, path=''):
        qs = self.filter(path__istartswith=path + '/') if path else self.all()
        out = SortedDict()
        for i in qs:
            ref = out
            col = []
            paths = i.path.split('/')
            for p in paths:
                if p not in ref:
                    ref[p] = [None, SortedDict()]
                col = ref[p]
                ref = ref[p][1]
            col[0] = i
        return out


class PathManager(models.Manager):
    def get_query_set(self):
        return PathQuerySet(self.model, using=self._db)
    
    def children(self, path=u'', depth=0):
        return self.get_query_set().children(path, depth)
    
    def tree(self, path=''):
        return self.get_query_set().tree(path)

    def cached_tree(self):
        tree = cache.get(PATH_TREE_CACHE_KEY)
        if tree is None:
            tree = self.tree()
            cache.set(PATH_TREE_CACHE_KEY, tree)
        return tree


class ModelBase(models.Model):
    model = models.CharField(u'内容模型', max_length=50, choices=((k, i['name']) for k, i in CONTENT_MODELS.items()))

    class Meta:
        abstract = True

    @property
    def model_config(self):
        return CONTENT_MODELS.get(self.model)

    @property
    def model_class(self):
        return import_object(self.model_config.get('model'))

    @property
    def form_class(self):
        return import_object(self.model_config.get('form'))


class Path(ModelBase):
    VIEW_INDEX = 1
    VIEW_LIST = 2
    VIEW_CONTENT = 3
    VIEW_CHOICES = (
        (VIEW_INDEX, u'首页'),
        (VIEW_LIST, u'列表'),
        (VIEW_CONTENT, u'内容'),
    )

    name = models.CharField(u'栏目名称', max_length=100)
    path = models.CharField(u'栏目路径', max_length=100, unique=True, help_text=PATH_HELP)
    depth = models.SmallIntegerField(u'栏目深度', db_index=True, editable=False)
    sort = models.SmallIntegerField(u'排序', db_index=True, default=0, editable=False)
    
    index_template = models.CharField(u'首页模版', max_length=100, blank=True, default='', help_text=INDEX_TEMPLATE_HELP)
    list_template = models.CharField(u'列表模版', max_length=100, blank=True, default='', help_text=LIST_TEMPLATE_HELP)
    list_per_page = models.PositiveSmallIntegerField(u'列表页数据分页条数', default=LIST_PER_PAGE)
    content_template = models.CharField(u'内容模版', max_length=200, blank=True, default='', help_text=CONTENT_TEMPLATE_HELP)
    default_view = models.SmallIntegerField(u'默认视图', choices=VIEW_CHOICES, default=VIEW_LIST, db_index=True)
    
    create_at = models.DateTimeField(u'创建日期', auto_now_add=True, db_index=True)
    update_at = models.DateTimeField(u'更新日期', auto_now=True, db_index=True)
    create_user = models.ForeignKey(User, null=True, on_delete=SET_NULL, editable=False, related_name='+')
    update_user = models.ForeignKey(User, null=True, on_delete=SET_NULL, editable=False, related_name='+')
    views = models.PositiveIntegerField(u'浏览量', db_index=True, default=0, editable=False)

    objects = PathManager()
    
    class Meta:
        ordering = ('id',)
        get_latest_by = ('id',)
    
    def __unicode__(self):
        return self.path
    
    @models.permalink
    def get_absolute_url(self):
        return 'cms-path', [self.path]

    url = property(get_absolute_url)
    
    @property
    def parent_path(self):
        if self.depth > 0:
            return '/'.join(self.path.split('/')[:-1])
        return ''
    
    def children(self, depth=PATH_DEPTH_FIRST):
        return Path.objects.children(self.path, depth)

    @cached_property
    def content_count(self):
        return ContentBase.objects.filter(path=self, is_deleted=False).count()
    
    # 同步更新内容中的 path 和 depth
    def update_content_path(self):
        ContentBase.objects.filter(path=self).update(path_value=self.path, path_depth=self.depth)


@receiver(signals.pre_save, sender=Path)
def on_path_pre_save(instance, **kwargs):
    instance.path = instance.path.strip(' /')
    instance.depth = instance.path.count('/')
    if not instance.pk:
        try:
            parent_last = Path.objects.children(instance.parent_path).latest()
            instance.sort = parent_last.sort + 1
        except Path.DoesNotExist:
            pass
    # 修改子栏目的父路径
    if instance.pk:
        p = Path.objects.get(pk=instance.pk)
        if p.path != instance.path:
            for i in p.children(PATH_DEPTH_ALL):
                path = instance.path + i.path[len(p.path):]
                update_instance(i, path=path)
                i.update_content_path()


@receiver(signals.post_save, sender=Path)
def on_path_post_save(instance, **kwargs):
    instance.update_content_path()
    cache.delete(PATH_TREE_CACHE_KEY)


class Collection(models.Model):
    name = models.CharField(u'集合名称', max_length=100, unique=True)

    class Meta:
        ordering = ['pk']
        verbose_name = u'内容集合'

    def __unicode__(self):
        return self.name

    @cached_property
    def content_count(self):
        return self.contentbase_set.filter(is_deleted=False).count()


class CollectionContent(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    contentbase = models.ForeignKey('ContentBase', on_delete=models.CASCADE)

    class Meta:
        auto_created = False
        ordering = ['-pk']
        db_table = 'cms_contentbase_collections'
        verbose_name = u'内容集合关联'

    def __unicode__(self):
        return self.contentbase.title


class ContentQuerySet(QuerySet):
    # 返回可用的内容
    def available(self):
        return self.filter(is_deleted=False, is_hidden=False)


class ContentManager(models.Manager):
    def get_query_set(self):
        return ContentQuerySet(self.model, using=self._db)
    
    def available(self):
        return self.get_query_set().available()


class ContentBase(ModelBase):
    path = models.ForeignKey(Path, editable=False, related_name='+')
    path_value = models.CharField(max_length=200, db_index=True, editable=False)  # 缓存字段:用于快速检索
    path_depth = models.SmallIntegerField(db_index=True, editable=False)  # 缓存字段:用于快速检索
    title = models.CharField(u'标题', max_length=200, null=True)
    create_at = models.DateTimeField(u'创建日期', auto_now_add=True, db_index=True)
    update_at = models.DateTimeField(u'更新日期', auto_now=True, db_index=True)
    create_user = models.ForeignKey(User, null=True, on_delete=SET_NULL, editable=False, related_name='+')
    update_user = models.ForeignKey(User, null=True, on_delete=SET_NULL, editable=False, related_name='+')
    views = models.PositiveIntegerField(u'浏览量', db_index=True, default=0, editable=False)
    flag = models.SmallIntegerField(u'标记为', default=0, db_index=True, choices=FLAGS)
    is_deleted = models.BooleanField(u'已删除?', db_index=True, default=False, editable=False)
    is_hidden = models.BooleanField(u'隐藏 (在前台不显示)', db_index=True, default=False)
    collections = models.ManyToManyField(Collection, blank=True, verbose_name=u'内容集合',
                                         help_text=u'可以将此内容归集到多个集合中。')
    objects = ContentManager()

    class Meta:
        ordering = ('-pk',)
        get_latest_by = ('pk', )

    def __unicode__(self):
        return self.title or ('Content: #%d' % self.pk)

    @models.permalink
    def get_absolute_url(self):
        return 'cms-content', [self.path_value, self.pk]

    url = property(get_absolute_url)
    
    def is_available(self):
        return not self.is_deleted and not self.is_hidden

    @property
    def model_name(self):
        return self.model_config.get('name')

    @cached_property
    def previous(self):
        try:
            return self.model_class.objects.filter(
                is_deleted=False, is_hidden=False, path=self.path, pk__lt=self.pk).order_by('pk')[0]
        except IndexError:
            pass

    @cached_property
    def next(self):
        try:
            return self.model_class.objects.filter(
                is_deleted=False, is_hidden=False, path=self.path, pk__gt=self.pk).order_by('-pk')[0]
        except IndexError:
            pass


########################################################################################################################

MENUS_CACHE_KEY = 'jiango.menus'


class Menu(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, verbose_name=u'父')

    title = models.CharField(u'标题', max_length=200)
    value = models.TextField(u'值')
    order = models.IntegerField(u'排序值', db_index=True, blank=True, help_text=u'不填写默认为最后一项')
    is_hidden = models.BooleanField(u'隐藏', default=False)

jiango/cms/templates/cms/admin/actions.inc.html
{% for a,i in actions.items %}
    <button type="submit" class="btn btn-sm {{i.button_class}}" name="action" value="{{a}}">
        {% if i.icon %}<i class="{{i.icon}}"></i> {% endif %}{{i.name}}
    </button>
{% endfor %}

jiango/cms/templates/cms/admin/collection-list-control.inc.html
{% load admin_pagination %}

<div class="pull-left">
    {% include 'cms/admin/actions.inc.html' %}
    {% if current %}
        <i class="sep">|</i>
        <a href="{% url admin:cms:collection-edit current.pk %}" class="btn btn-sm btn-default"><i class="fa fa-edit"></i> 修改集合</a>
    {% endif %}
</div>
<div class="pull-right">
    {% paginate content_set %}
</div>

jiango/cms/templates/cms/admin/collection.html
<section class="content">
    <div class="row">
        <div data-spy="affix" style="float:left;width:250px;margin-left:20px;">
            <div class="list-group">
                <a class="list-group-item{% if not current %} active{% endif %}" href="{% url admin:cms:collection %}">全部集合
                    <span class="badge">{{ total_content_count }}</span>
                </a>
            </div>
            <div class="list-group">
            {% for p in collection_set %}
                <a class="list-group-item{% if current == p %} active{% endif %}" href="{% url admin:cms:collection-show p.pk %}">{{ p.name }}
                    <span class="badge">{{ p.content_count }}</span>
                </a>
            {% endfor %}
            </div>
            <div class="list-group">
                <a class="list-group-item" href="{% url admin:cms:collection-create %}">
                    <i class="fa fa-plus"></i> 创建集合
                </a>
            </div>
        </div>
        <div style="float:right;width:calc(100% - 310px);margin-right:20px;">
            <form action="{% url admin:cms:collection-action %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="back" value="{{request.get_full_path|escape}}">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <td colspan="{{ current|yesno:'8,9' }}">{% include 'cms/admin/collection-list-control.inc.html' %}</td>
                        </tr>
                        <tr>
                            <th class="nowrap"><input type="checkbox" data-spy="checkall" data-for="[name='pk']"></th>
                            <th class="number">ID</th>
                            <th class="nowrap">模型</th>
                            <th class="nowrap">栏目</th>
                            {% if not current %}<th class="nowrap">集合</th>{% endif %}
                            <th>标题</th>
                            <th class="datetime">修改日期</th>
                            <th class="user">修改人</th>
                            <th class="number">浏览量</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in content_set %}
                        <tr>
                            <td class="nowrap"><input type="checkbox" name="pk" value="{{i.pk}}"></td>
                            <td class="number">{{i.contentbase.pk}}</td>
                            <td class="nowrap">{{ i.contentbase.model_name }}</td>
                            <td class="nowrap"><a href="{% url admin:cms:content-path i.contentbase.path.path %}">{{ i.contentbase.path.name }}</a></td>
                            {% if not current %}<td class="nowrap"><a href="{% url admin:cms:collection-show i.pk %}">{{ i.collection.name }}</a></td>{% endif %}
                            <td>
                                {% if i.contentbase.is_hidden %}<span class="label label-default">隐藏</span>{% endif %}
                                <a href="{% url admin:cms:content-edit i.contentbase.pk %}">{{i.contentbase}}</a>
                                <div class="pull-right">
                                    <a href="{{ i.contentbase.url }}" class="btn btn-xs btn-default" target="_blank">查看</a>
                                </div>
                            </td>
                            <td class="datetime">{{i.contentbase.update_at}}</td>
                            <td class="user">{{i.contentbase.update_user}}</td>
                            <td class="number">{{i.contentbase.views}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="{{ path|yesno:'8,9' }}">
                                {% include 'cms/admin/collection-list-control.inc.html' %}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </form>
        </div>
    </div>
</section>

jiango/cms/templates/cms/admin/column.html
<section class="content">
        <table class="table">
            <thead>
                <tr>
                    <th class="number">ID</th>
                    <th class="nowrap">模型</th>
                    <th>路径</th>
                    <th class="nowrap">栏目名称</th>
                    <th class="datetime">修改日期</th>
                    <th class="user">修改人</th>
                    <th class="number">浏览量</th>
                </tr>
            </thead>
            <tbody>
                {% for i in column_set %}
                <tr>
                    <td class="number">{{i.pk}}</td>
                    <td class="nowrap">{{i.get_model_display|default:'不可发布'}}</td>
                    <td><a href="{{i.get_absolute_url}}" target="_blank">{{i.path}}</a>
                        <div class="pull-right">
                            <a href="{% url admin:cms:column-edit i.pk %}">修改</a>
                            <a href="{% url admin:cms:column-delete i.pk %}">删除</a>
                        </div>
                    </td>
                    <td class="nowrap">{{i.name}}</td>
                    <td class="datetime">{{i.update_at}}</td>
                    <td class="user">{{i.update_user}}</td>
                    <td class="number">{{i.views}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url admin:cms:column-create %}" class="btn btn-default"><i class="icon-plus"></i> 新建栏目</a>
</section>

jiango/cms/templates/cms/admin/column_edit.html
<section class="content">
        <ul class="breadcrumb">
          <li><a href="{% url admin:cms:column %}">栏目管理</a></li>
          <li class="active">{% if instance %}修改栏目{% else %}创建栏目{% endif %}</li>
        </ul>
        <form method="post" action="" class="form" id="form">
            {% csrf_token %}
            {{form|bootstrap}}
            <div style="text-align:center;margin-top:30px">
                <button type="submit" class="btn btn-warning btn-large">确定</button>
            </div>
        </form>
</section>

jiango/cms/templates/cms/admin/content-list-control.inc.html
{% load admin_pagination %}

<div class="pull-left">
    {% for a,i in actions.items %}
        <button type="submit" class="btn btn-sm {{i.button_class}}" name="action" value="{{a}}">
            {% if i.icon %}<i class="{{i.icon}}"></i> {% endif %}{{i.name}}
        </button>
    {% endfor %}
    {% if can_create_content %}
        <i class="sep">|</i>
        <a href="{% url admin:cms:content-create current_path.path %}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> 添加内容</a>
    {% endif %}
</div>
<div class="pull-right">
    {% paginate content_set %}
</div>

jiango/cms/templates/cms/admin/content.html
<section class="content">
    <div class="row">
        <div data-spy="affix" style="float:left;width:250px;margin-left:20px;">
            <div class="list-group">
                <a class="list-group-item{% if not path %} active{% endif %}" href="{% url admin:cms:content %}">全部栏目
                    <span class="badge">{{ total_content_count }}</span>
                </a>
            </div>
            <div class="list-group">
            {% for p in paths %}
                <a class="list-group-item{% if path == p %} active{% endif %}" href="{% url admin:cms:content-path p.path %}"><span style="margin-left:{{ p.depth }}em">{{ p.name }}</span>
                    <span class="badge">{{ p.content_count }}</span>
                </a>
            {% endfor %}
            </div>
            <div class="list-group">
                <a class="list-group-item" href="{% url admin:cms:path-create %}">
                    <i class="fa fa-plus"></i> 创建栏目
                </a>
            </div>
        </div>
        <div style="float:right;width:calc(100% - 310px);margin-right:20px;">
            <form action="{% url admin:cms:content-action %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="back" value="{{request.get_full_path|escape}}">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <td colspan="{{ path|yesno:'7,8' }}">{% include 'cms/admin/content-list-control.inc.html' %}</td>
                        </tr>
                        <tr>
                            <th class="nowrap"><input type="checkbox" data-spy="checkall" data-for="[name='pk']"></th>
                            <th class="number">ID</th>
                            <th class="nowrap">模型</th>
                            {% if not path %}<th class="nowrap">栏目</th>{% endif %}
                            <th>标题</th>
                            <th class="datetime">修改日期</th>
                            <th class="user">修改人</th>
                            <th class="number">浏览量</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in content_set %}
                        <tr>
                            <td class="nowrap"><input type="checkbox" name="pk" value="{{i.pk}}"></td>
                            <td class="number">{{i.pk}}</td>
                            <td class="nowrap">{{ i.model_name }}</td>
                            {% if not path %}<td class="nowrap"><a href="{% url admin:cms:content-path i.path.path %}">{{ i.path.name }}</a></td>{% endif %}
                            <td>
                                {% if i.flag != 0 %}<span class="label label-info">{{ i.get_flag_display }}</span>{% endif %}
                                {% if i.is_hidden %}<span class="label label-default">隐藏</span>{% endif %}
                                <a href="{% url admin:cms:content-edit i.pk %}">{{i}}</a>
                                {% if i.url %}
                                <div class="pull-right">
                                    <a href="{{ i.url }}" class="btn btn-xs btn-default" target="_blank">查看</a>
                                </div>
                                {% endif %}
                            </td>
                            <td class="datetime">{{i.update_at}}</td>
                            <td class="user">{{i.update_user}}</td>
                            <td class="number">{{i.views}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="{{ path|yesno:'7,8' }}">
                                {% include 'cms/admin/content-list-control.inc.html' %}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </form>
        </div>
    </div>
</section>

jiango/cms/templates/cms/admin/content_action.html
{% load admin_pagination %}

<section class="content">
        <ul class="breadcrumb">
          <li><a href="{% url admin:cms:content %}">内容管理</a></li>
          <li>批量操作: {{action_name}}</li>
        </ul>
        <form action="" method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="__action_form_data" value="{{action_form_data|escape}}">
            <input type="hidden" name="__confirm" value="yes">
            <table style="width:100%"><tr>
                <td style="vertical-align:top;">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="number">ID</th>
                                <th class="nowrap">所属路径</th>
                                <th>标题</th>
                                <th class="datetime">修改日期</th>
                                <th class="user">修改人</th>
                                <th class="number">浏览量</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in content_set %}
                            <tr>
                                <td class="number">{{i.pk}}</td>
                                <td class="nowrap">
                                    <a href="{{i.path.get_absolute_url}}" target="_blank">{{i.path.name}}</a>
                                </td>
                                <td><a href="{{i.get_absolute_url}}" target="_blank">{{i}}</a>
                                    {% if i.is_hidden %}<span class="label">隐藏</span>{% endif %}
                                </td>
                                <td class="datetime">{{i.update_at}}</td>
                                <td class="user">{{i.update_user}}</td>
                                <td class="number">{{i.views}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
                <td style="width:180px;padding-left:20px;vertical-align:top;">
                    <div data-spy="affix" data-offset-top="100" style="width:180px;top:50px">
                        {% if back %}
                            <a href="{{back}}" class="btn btn-default btn-block"><i class="icon-arrow-left"></i> 返回</a>
                        {% endif %}
                        <button type="submit" class="btn btn-success btn-large btn-block" style="margin-bottom:10px;">确定{{action_name}}</button>
                        {{form|bootstrap}}
                    </div>
                </td>
            </tr></table>
        </form>
</section>

jiango/cms/templates/cms/admin/path.html
<section class="content">
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="number">ID</th>
                    <th class="nowrap">模型</th>
                    <th class="nowrap">视图</th>
                    <th>名称</th>
                    <th class="datetime">修改日期</th>
                    <th class="user">修改人</th>
                    <th class="number">浏览量</th>
                </tr>
            </thead>
            <tbody>
                {% for i in path_set %}
                <tr>
                    <td class="number">{{i.pk}}</td>
                    <td class="nowrap">{{i.get_model_display|default:'不可发布'}}</td>
                    <td class="nowrap">{{i.get_default_view_display}}</td>
                    <td><a href="{% url admin:cms:path-edit i.pk %}"><span style="margin-left:{{ i.depth }}em">{{ i.name }}</span></a>
                        <div class="pull-right">
                            <small>{{i.path}}</small>
                            <i class="sep">|</i>
                            {% if i.get_absolute_url %}
                            <a href="{{i.get_absolute_url}}" target="_blank" class="btn btn-success btn-xs">查看</a>
                            {% endif %}
                            <a href="{% url admin:cms:path-delete i.pk %}" class="btn btn-danger btn-xs">删除</a>
                        </div>
                    </td>
                    <td class="datetime">{{i.update_at}}</td>
                    <td class="user">{{i.update_user}}</td>
                    <td class="number">{{i.views}}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <a href="{% url admin:cms:path-create %}" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> 新建栏目</a>
                    </td>
                </tr>
            </tfoot>
        </table>
</section>

jiango/cms/templates/cms/admin/path_edit.html
<section class="content">
        <ul class="breadcrumb">
          <li><a href="{% url admin:cms:path %}">路径管理</a></li>
          <li class="active">{% if instance %}修改路径{% else %}创建路径{% endif %}</li>
        </ul>
        <form method="post" action="" class="form" id="form">
            {% csrf_token %}
            {{form|bootstrap}}
            <div style="text-align:center;margin-top:30px">
                <button type="submit" class="btn btn-warning btn-large">确定</button>
            </div>
        </form>
</section>

jiango/cms/templates/cms/admin/recycle.html
{% load admin_pagination %}
{% load bootstrap %}

<section class="content">
        {% if is_clear_mode %}

            <blockquote>
                <h2>清空回收站确认</h2>
                <p>将要被清空的数量为: <strong>{{content_count}}</strong></p>
                <form action="" method="post" style="margin-top:20px">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">
                        <i class="icon-fire icon-white"></i> 确定清空
                    </button>
                </form>
            </blockquote>

        {% elif content_set %}

            <form action="" method="post">
                {% csrf_token %}
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th class="nowrap"><input type="checkbox" data-spy="checkall" data-for="[name='pk']"></th>
                            <th class="number">ID</th>
                            <th class="nowrap">栏目</th>
                            <th>标题</th>
                            <th class="datetime">修改日期</th>
                            <th class="user">修改人</th>
                            <th class="number">浏览量</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in content_set %}
                        <tr>
                            <td><input type="checkbox" name="pk" value="{{i.pk}}"></td>
                            <td class="number">{{i.pk}}</td>
                            <td class="nowrap">
                                <a href="{{i.path.get_absolute_url}}" target="_blank">{{i.path.name}}</a>
                            </td>
                            <td><a href="{% url admin:cms:content-edit i.pk %}?next={{request.get_full_path|urlencode}}">{{i}}</a>
                                {% if i.is_hidden %}<span class="label">隐藏</span>{% endif %}
                            </td>
                            <td class="datetime">{{i.update_at}}</td>
                            <td class="user">{{i.update_user}}</td>
                            <td class="number">{{i.views}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="7">
                                <div class="pull-left">
                                    <button type="submit" class="btn btn-default btn-sm" name="action" value="fire">
                                        <i class="fa fa-remove"></i> 彻底删除选中项
                                    </button>
                                    <i class="sep">|</i>
                                    <a href="{% url admin:cms:recycle-clear %}" class="btn btn-danger btn-sm"><i class="fa fa-recycle"></i> 清空回收站</a>
                                </div>
                                <div class="pull-right">
                                    {% paginate content_set %}
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </form>

        {% else %}
            <h2 style="text-align:center;">回收站中没有任何内容</h2>
        {% endif %}
</section>